<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jacob Caraccilo">
<meta name="description" content="Proposal for a data visualization project using the 2025 TidyTuesday Water Insecurity dataset to investigate patterns of water insecurity across U.S. counties.">

<title>Investigating Water Insecurity in the United States – Project Title</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-f418161beb48e0141c760e455f12af2c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b0e73cb451bbb7631af6acf6dae58723.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-aaa1e35cf1f5b6230ece6ed5b6fa3d4a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-b0e73cb451bbb7631af6acf6dae58723.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Project Title</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./proposal.html" aria-current="page"> 
<span class="menu-text">Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.html"> 
<span class="menu-text">Presentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/INFO-526-SU24/project-01"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-tidytuesday-water-insecurity-dataset" id="toc-the-tidytuesday-water-insecurity-dataset" class="nav-link active" data-scroll-target="#the-tidytuesday-water-insecurity-dataset">The TidyTuesday Water Insecurity Dataset</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions</a></li>
  <li><a href="#analysis-plan" id="toc-analysis-plan" class="nav-link" data-scroll-target="#analysis-plan">Analysis plan</a>
  <ul class="collapse">
  <li><a href="#step-1-identify-and-download-u.s.-census-bureau-data" id="toc-step-1-identify-and-download-u.s.-census-bureau-data" class="nav-link" data-scroll-target="#step-1-identify-and-download-u.s.-census-bureau-data">Step 1: Identify and Download U.S. Census Bureau Data</a></li>
  <li><a href="#step-2-complete-data-processing-and-cleaning-to-fully-integrate-u.s.-census-bureau-data-with-tidytuesday-dataset" id="toc-step-2-complete-data-processing-and-cleaning-to-fully-integrate-u.s.-census-bureau-data-with-tidytuesday-dataset" class="nav-link" data-scroll-target="#step-2-complete-data-processing-and-cleaning-to-fully-integrate-u.s.-census-bureau-data-with-tidytuesday-dataset">Step 2: Complete Data Processing and Cleaning to Fully Integrate U.S. Census Bureau Data with TidyTuesday Dataset</a></li>
  <li><a href="#step-3-addressing-question-1-construct-visualizations-of-water-insecurity-rates-against-demographic-and-economic-parameters" id="toc-step-3-addressing-question-1-construct-visualizations-of-water-insecurity-rates-against-demographic-and-economic-parameters" class="nav-link" data-scroll-target="#step-3-addressing-question-1-construct-visualizations-of-water-insecurity-rates-against-demographic-and-economic-parameters">Step 3: Addressing Question 1: Construct visualizations of Water Insecurity Rates against Demographic and Economic Parameters</a></li>
  <li><a href="#step-4-addressing-question-2-compare-2022-data-to-2023-data-using-the-same-methods-to-determine-yearly-trends" id="toc-step-4-addressing-question-2-compare-2022-data-to-2023-data-using-the-same-methods-to-determine-yearly-trends" class="nav-link" data-scroll-target="#step-4-addressing-question-2-compare-2022-data-to-2023-data-using-the-same-methods-to-determine-yearly-trends">Step 4: Addressing Question 2: Compare 2022 Data to 2023 Data Using the Same Methods to Determine Yearly Trends</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Investigating Water Insecurity in the United States</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">INFO 526 Final Project Proposal</p>
</div>

<div>
  <div class="description">
    Proposal for a data visualization project using the 2025 TidyTuesday Water Insecurity dataset to investigate patterns of water insecurity across U.S. counties.
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Jacob Caraccilo </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            School of Information, University of Arizona
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># provides glimpse at 2022 water insecurity data</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">glimpse</span>(water_insecurity_2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 848
Columns: 7
$ geoid                    &lt;chr&gt; "01069", "04001", "06037", "06097", "06001", …
$ name                     &lt;chr&gt; "Houston County, Alabama", "Apache County, Ar…
$ year                     &lt;dbl&gt; 2022, 2022, 2022, 2022, 2022, 2022, 2022, 202…
$ geometry                 &lt;chr&gt; "list(list(c(975267.980555021, 975512.9445474…
$ total_pop                &lt;dbl&gt; 108079, 65432, 9721138, 482650, 1628997, 8978…
$ plumbing                 &lt;dbl&gt; 93, 2440, 6195, 148, 808, 18, 128, 0, 123, 13…
$ percent_lacking_plumbing &lt;dbl&gt; 0.08604817, 3.72906223, 0.06372711, 0.0306640…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># provides glimpse at 2023 water insecurity data</span></span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="fu">glimpse</span>(water_insecurity_2023)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 854
Columns: 7
$ geoid                    &lt;chr&gt; "01003", "01069", "06037", "06087", "06097", …
$ name                     &lt;chr&gt; "Baldwin County, Alabama", "Houston County, A…
$ year                     &lt;dbl&gt; 2023, 2023, 2023, 2023, 2023, 2023, 2023, 202…
$ geometry                 &lt;chr&gt; "list(list(c(765297.99052762, 765703.76567671…
$ total_pop                &lt;dbl&gt; 253507, 108462, 9663345, 261547, 481812, 1155…
$ plumbing                 &lt;dbl&gt; 271, 30, 5248, 187, 308, 517, 4, 198, 1269, 8…
$ percent_lacking_plumbing &lt;dbl&gt; 0.106900401, 0.027659457, 0.054308317, 0.0714…</code></pre>
</div>
</div>
<section id="the-tidytuesday-water-insecurity-dataset" class="level2">
<h2 class="anchored" data-anchor-id="the-tidytuesday-water-insecurity-dataset">The TidyTuesday Water Insecurity Dataset</h2>
<p>The ‘Water Insecurity’ Dataset was published on January 28th of 2025 for TidyTuesday and was curated by Niha Pereira. It explores household access to water across U.S. counties and allows us to investigate regional and population-related patterns for water insecurity. Combined with demographic data, it can also provide insight into social and economic factors that may contribute to rates of water insecurity across the U.S.</p>
<p>The data includes two separate datasets for 2022 and 2023, each covering the extent of water insecurity (defined as a household lacking full plumbing infrastructure) in approximately 850 counties. This data is directly drawn from the U.S. Census Bureau and was developed through surveys of the public, meaning totals for those who are water insecure are estimates.</p>
<p>The 2022 dataset includes 848 counties, while the 2023 dataset includes 854. They both contain 7 parameters:</p>
<ul>
<li><p><code>geoid</code>: A character variable of a unique county identifier code used by the U.S. Census Bureau.</p></li>
<li><p><code>name</code>: A character variable of the name of the U.S. county.</p></li>
<li><p><code>year</code>: A numerical variable of the year the data was collected (constant for each dataset).</p></li>
<li><p><code>geometry</code>: A spatial geometry object that contains the geographic boundaries for each county in the dataset. Used to plot geographic maps of the U.S.</p></li>
<li><p><code>total_pop</code>: A numerical variable representing the population of a given county.</p></li>
<li><p><code>plumbing</code>: A numerical variable representing the estimated number of people in the county who are water insecure, defined as their household lacking full plumbing.</p></li>
<li><p><code>percent_lacking_plumbing</code>: A numerical variable of the percent of people in a county who are water insecure; a ratio of <code>plumbing</code> and <code>total_pop</code>.</p></li>
</ul>
<p>I chose this dataset due to personal interest in water accessibility. I live in the California Central Valley which has struggled with water shortages and droughts for decades. I am interested in investigating and identifying demographic and economic factors that correlate with water insecurity and providing insight into the causes of water insecurity in my region and across the U.S.</p>
</section>
<section id="questions" class="level2">
<h2 class="anchored" data-anchor-id="questions">Questions</h2>
<p>Two major questions I plan to investigate surround demographic factors and how the rate of water insecurity is changing over time.</p>
<ul>
<li><p>What demographic and economic factors are correlated with higher and lower rates of water insecurity?</p></li>
<li><p>Which regions saw the biggest changes in water insecurity rates from 2022 to 2023? Did those regions improve or worsen? Does the presence of certain demographic, regional, or economic factors appear correlated to these changes in water insecurity rates?</p></li>
</ul>
</section>
<section id="analysis-plan" class="level2">
<h2 class="anchored" data-anchor-id="analysis-plan">Analysis plan</h2>
<p>For both of these questions, we will need to gather demographic data from the U.S. Census Bureau and will likely have to begin with answering question one to help inform our conclusions regarding question two. The following steps are proposed.</p>
<section id="step-1-identify-and-download-u.s.-census-bureau-data" class="level3">
<h3 class="anchored" data-anchor-id="step-1-identify-and-download-u.s.-census-bureau-data">Step 1: Identify and Download U.S. Census Bureau Data</h3>
<p>The TidyTuesday dataset does not include any demographic information for U.S. counties aside from population. Because of this, we will have to use additional external data from the U.S. Census Bureau. We will gather demographic and income data from relevant counties, including the following parameters:</p>
<p>• Median Household Income</p>
<p>• % African American</p>
<p>• % Hispanic/Latino</p>
<p>• % White</p>
<p>• % Asian</p>
<p>•&nbsp;% Native</p>
</section>
<section id="step-2-complete-data-processing-and-cleaning-to-fully-integrate-u.s.-census-bureau-data-with-tidytuesday-dataset" class="level3">
<h3 class="anchored" data-anchor-id="step-2-complete-data-processing-and-cleaning-to-fully-integrate-u.s.-census-bureau-data-with-tidytuesday-dataset">Step 2: Complete Data Processing and Cleaning to Fully Integrate U.S. Census Bureau Data with TidyTuesday Dataset</h3>
<p>Upon collecting all external data from the U.S. Census Bureau, we will complete data processing and cleaning to integrate all of the data into a single dataframe that we can use for analysis. This will include standardizing column names, removing extra data from counties not present in the TidyTuesday dataset, resolving issues with missing data, and any other data cleaning necessary to make the dataset easily usable for analysis.</p>
<p>All of the previously mentioned parameters will be added to the water insecurity datasets, and we will also manually create a region related parameter based on U.S. Census Bureau definitions.</p>
<p>• West: Washington, Oregon, California, Alaska, Hawaii, Montana, Idaho, Wyoming, Colorado, New Mexico, Arizona, Utah, Nevada</p>
<p>• South: Delaware, Maryland, District of Columbia, Virginia, West Virginia, North Carolina, South Carolina, Georgia, Florida, Kentucky, Tennessee, Mississippi, Alabama, Arkansas, Louisiana, Oklahoma, Texas</p>
<p>• Midwest: Ohio, Indiana, Illinois, Michigan, Wisconsin, Minnesota, Iowa, Missouri, North Dakota, South Dakota, Nebraska, Kansas</p>
<p>• Northeast: Maine, New Hampshire, Vermont, Massachusetts, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania</p>
</section>
<section id="step-3-addressing-question-1-construct-visualizations-of-water-insecurity-rates-against-demographic-and-economic-parameters" class="level3">
<h3 class="anchored" data-anchor-id="step-3-addressing-question-1-construct-visualizations-of-water-insecurity-rates-against-demographic-and-economic-parameters">Step 3: Addressing Question 1: Construct visualizations of Water Insecurity Rates against Demographic and Economic Parameters</h3>
<p>Once data processing is completed and all new parameters are collected or created, we will create visualizations comparing our parameters to rates of water insecurity across all available counties. We will initially only work with the 2022 dataset.</p>
<p>The following visualization types are proposed:<br>
<br>
• Boxplots: Necessary to gather summarizing statistical information about all demographic groups and median income.</p>
<p>•&nbsp;Density Plots: Helpful at identifying clusters of data that the boxplots would fail to show.</p>
<p>• Linear Regression Plots: Tells us the specific strength of the relationship between water insecurity and demographics.</p>
</section>
<section id="step-4-addressing-question-2-compare-2022-data-to-2023-data-using-the-same-methods-to-determine-yearly-trends" class="level3">
<h3 class="anchored" data-anchor-id="step-4-addressing-question-2-compare-2022-data-to-2023-data-using-the-same-methods-to-determine-yearly-trends">Step 4: Addressing Question 2: Compare 2022 Data to 2023 Data Using the Same Methods to Determine Yearly Trends</h3>
<p>After identifying any trends among the rate of water insecurity and our demographic and economic parameters, we can compare the year to year data to see if there are any changes from 2022 to 2023. We do have to be careful not to project too much based off this analysis since we’re only looking at two years. However, we can use this data to identify any major changes that occur. Furthermore, we can use this opportunity to see if specific parameters are correlated with certain changes in water insecurity rates from 2022 and 2023.</p>
<p>We will examine which regions of the country saw the biggest shifts in rates of water insecurity. This will be done by using the three visualization methods mentioned previously to create 2022 and 2023 plots of counties in each region of the country and their rates of water insecurity. I will also create a new variable to calculate the change in the water insecurity rate from 2022 to 2023 to visualize that shift.</p>
<p>After this, we will also create side-by-side comparisons of the visualizations from Step 3 to see if any of our demographic or economic parameters are correlated with changes from 2022 to 2023.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        const annoteTargets = window.document.querySelectorAll('.code-annotation-anchor');
        for (let i=0; i<annoteTargets.length; i++) {
          const annoteTarget = annoteTargets[i];
          const targetCell = annoteTarget.getAttribute("data-target-cell");
          const targetAnnotation = annoteTarget.getAttribute("data-target-annotation");
          const contentFn = () => {
            const content = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
            if (content) {
              const tipContent = content.cloneNode(true);
              tipContent.classList.add("code-annotation-tip-content");
              return tipContent.outerHTML;
            }
          }
          const config = {
            allowHTML: true,
            content: contentFn,
            onShow: (instance) => {
              selectCodeLines(instance.reference);
              instance.reference.classList.add('code-annotation-active');
              window.tippy.hideAll();
            },
            onHide: (instance) => {
              unselectCodeLines();
              instance.reference.classList.remove('code-annotation-active');
            },
            maxWidth: 300,
            delay: [50, 0],
            duration: [200, 0],
            offset: [5, 10],
            arrow: true,
            appendTo: function(el) {
              return el.parentElement.parentElement.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'quarto',
            placement: 'right',
            popperOptions: {
              modifiers: [
              {
                name: 'flip',
                options: {
                  flipVariations: false, // true by default
                  allowedAutoPlacements: ['right'],
                  fallbackPlacements: ['right', 'top', 'top-start', 'top-end', 'bottom', 'bottom-start', 'bottom-end', 'left'],
                },
              },
              {
                name: 'preventOverflow',
                options: {
                  mainAxis: false,
                  altAxis: false
                }
              }
              ]        
            }      
          };
          window.tippy(annoteTarget, config); 
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb5-1"><a href="#cb5-1"></a><span class="co">---</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="an">title:</span><span class="co"> "Investigating Water Insecurity in the United States"</span></span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="an">subtitle:</span><span class="co"> "INFO 526 Final Project Proposal"</span></span>
<span id="cb5-4"><a href="#cb5-4"></a><span class="an">author:</span></span>
<span id="cb5-5"><a href="#cb5-5"></a><span class="co">  - name: "Jacob Caraccilo"</span></span>
<span id="cb5-6"><a href="#cb5-6"></a><span class="co">    affiliations:</span></span>
<span id="cb5-7"><a href="#cb5-7"></a><span class="co">      - name: "School of Information, University of Arizona"</span></span>
<span id="cb5-8"><a href="#cb5-8"></a><span class="an">description:</span><span class="co"> "Proposal for a data visualization project using the 2025 TidyTuesday Water Insecurity dataset to investigate patterns of water insecurity across U.S. counties."</span></span>
<span id="cb5-9"><a href="#cb5-9"></a><span class="an">format:</span></span>
<span id="cb5-10"><a href="#cb5-10"></a><span class="co">  html:</span></span>
<span id="cb5-11"><a href="#cb5-11"></a><span class="co">    code-tools: true</span></span>
<span id="cb5-12"><a href="#cb5-12"></a><span class="co">    code-overflow: wrap</span></span>
<span id="cb5-13"><a href="#cb5-13"></a><span class="co">    code-line-numbers: true</span></span>
<span id="cb5-14"><a href="#cb5-14"></a><span class="co">    embed-resources: true</span></span>
<span id="cb5-15"><a href="#cb5-15"></a><span class="an">editor:</span><span class="co"> visual</span></span>
<span id="cb5-16"><a href="#cb5-16"></a><span class="an">code-annotations:</span><span class="co"> hover</span></span>
<span id="cb5-17"><a href="#cb5-17"></a><span class="an">execute:</span></span>
<span id="cb5-18"><a href="#cb5-18"></a><span class="co">  warning: false</span></span>
<span id="cb5-19"><a href="#cb5-19"></a><span class="co">---</span></span>
<span id="cb5-20"><a href="#cb5-20"></a></span>
<span id="cb5-23"><a href="#cb5-23"></a><span class="in">```{r}</span></span>
<span id="cb5-24"><a href="#cb5-24"></a><span class="co">#| label: load-pkgs</span></span>
<span id="cb5-25"><a href="#cb5-25"></a><span class="co">#| message: false</span></span>
<span id="cb5-26"><a href="#cb5-26"></a><span class="co">#| echo: false</span></span>
<span id="cb5-27"><a href="#cb5-27"></a></span>
<span id="cb5-28"><a href="#cb5-28"></a><span class="co"># installs pacman if not already installed</span></span>
<span id="cb5-29"><a href="#cb5-29"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"pacman"</span>)) </span>
<span id="cb5-30"><a href="#cb5-30"></a>  <span class="fu">install.packages</span>(<span class="st">"pacman"</span>)</span>
<span id="cb5-31"><a href="#cb5-31"></a></span>
<span id="cb5-32"><a href="#cb5-32"></a><span class="co"># installs a list of packages when listed in p_load</span></span>
<span id="cb5-33"><a href="#cb5-33"></a> pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse,</span>
<span id="cb5-34"><a href="#cb5-34"></a>                tidytuesdayR,</span>
<span id="cb5-35"><a href="#cb5-35"></a>                sf,</span>
<span id="cb5-36"><a href="#cb5-36"></a>                kableExtra)</span>
<span id="cb5-37"><a href="#cb5-37"></a> </span>
<span id="cb5-38"><a href="#cb5-38"></a><span class="co"># loads in TidyTuesday Water Insecurity Dataset</span></span>
<span id="cb5-39"><a href="#cb5-39"></a>tuesdata <span class="ot">&lt;-</span> tidytuesdayR<span class="sc">::</span><span class="fu">tt_load</span>(<span class="st">'2025-01-28'</span>)</span>
<span id="cb5-40"><a href="#cb5-40"></a> </span>
<span id="cb5-41"><a href="#cb5-41"></a><span class="co"># sets the 2022 and 2023 data to their own variables</span></span>
<span id="cb5-42"><a href="#cb5-42"></a>water_insecurity_2022 <span class="ot">&lt;-</span> tuesdata<span class="sc">$</span>water_insecurity_2022</span>
<span id="cb5-43"><a href="#cb5-43"></a>water_insecurity_2023 <span class="ot">&lt;-</span> tuesdata<span class="sc">$</span>water_insecurity_2023</span>
<span id="cb5-44"><a href="#cb5-44"></a><span class="in">```</span></span>
<span id="cb5-45"><a href="#cb5-45"></a></span>
<span id="cb5-48"><a href="#cb5-48"></a><span class="in">```{r}</span></span>
<span id="cb5-49"><a href="#cb5-49"></a><span class="co"># provides glimpse at 2022 water insecurity data</span></span>
<span id="cb5-50"><a href="#cb5-50"></a><span class="fu">glimpse</span>(water_insecurity_2022)</span>
<span id="cb5-51"><a href="#cb5-51"></a><span class="in">```</span></span>
<span id="cb5-52"><a href="#cb5-52"></a></span>
<span id="cb5-55"><a href="#cb5-55"></a><span class="in">```{r}</span></span>
<span id="cb5-56"><a href="#cb5-56"></a><span class="co"># provides glimpse at 2023 water insecurity data</span></span>
<span id="cb5-57"><a href="#cb5-57"></a><span class="fu">glimpse</span>(water_insecurity_2023)</span>
<span id="cb5-58"><a href="#cb5-58"></a><span class="in">```</span></span>
<span id="cb5-59"><a href="#cb5-59"></a></span>
<span id="cb5-60"><a href="#cb5-60"></a><span class="fu">## The TidyTuesday Water Insecurity Dataset</span></span>
<span id="cb5-61"><a href="#cb5-61"></a></span>
<span id="cb5-62"><a href="#cb5-62"></a>The 'Water Insecurity' Dataset was published on January 28th of 2025 for TidyTuesday and was curated by Niha Pereira. It explores household access to water across U.S. counties and allows us to investigate regional and population-related patterns for water insecurity. Combined with demographic data, it can also provide insight into social and economic factors that may contribute to rates of water insecurity across the U.S.</span>
<span id="cb5-63"><a href="#cb5-63"></a></span>
<span id="cb5-64"><a href="#cb5-64"></a>The data includes two separate datasets for 2022 and 2023, each covering the extent of water insecurity (defined as a household lacking full plumbing infrastructure) in approximately 850 counties. This data is directly drawn from the U.S. Census Bureau and was developed through surveys of the public, meaning totals for those who are water insecure are estimates.</span>
<span id="cb5-65"><a href="#cb5-65"></a></span>
<span id="cb5-66"><a href="#cb5-66"></a>The 2022 dataset includes <span class="in">`r nrow(water_insecurity_2022)`</span> counties, while the 2023 dataset includes <span class="in">`r nrow(water_insecurity_2023)`</span>. They both contain <span class="in">`r ncol(water_insecurity_2022)`</span> parameters:</span>
<span id="cb5-67"><a href="#cb5-67"></a></span>
<span id="cb5-68"><a href="#cb5-68"></a><span class="ss">- </span><span class="in">`geoid`</span>: A character variable of a unique county identifier code used by the U.S. Census Bureau.</span>
<span id="cb5-69"><a href="#cb5-69"></a></span>
<span id="cb5-70"><a href="#cb5-70"></a><span class="ss">- </span><span class="in">`name`</span>: A character variable of the name of the U.S. county.</span>
<span id="cb5-71"><a href="#cb5-71"></a></span>
<span id="cb5-72"><a href="#cb5-72"></a><span class="ss">- </span><span class="in">`year`</span>: A numerical variable of the year the data was collected (constant for each dataset).</span>
<span id="cb5-73"><a href="#cb5-73"></a></span>
<span id="cb5-74"><a href="#cb5-74"></a><span class="ss">- </span><span class="in">`geometry`</span>: A spatial geometry object that contains the geographic boundaries for each county in the dataset. Used to plot geographic maps of the U.S.</span>
<span id="cb5-75"><a href="#cb5-75"></a></span>
<span id="cb5-76"><a href="#cb5-76"></a><span class="ss">- </span><span class="in">`total_pop`</span>: A numerical variable representing the population of a given county.</span>
<span id="cb5-77"><a href="#cb5-77"></a></span>
<span id="cb5-78"><a href="#cb5-78"></a><span class="ss">- </span><span class="in">`plumbing`</span>: A numerical variable representing the estimated number of people in the county who are water insecure, defined as their household lacking full plumbing.</span>
<span id="cb5-79"><a href="#cb5-79"></a></span>
<span id="cb5-80"><a href="#cb5-80"></a><span class="ss">- </span><span class="in">`percent_lacking_plumbing`</span>: A numerical variable of the percent of people in a county who are water insecure; a ratio of <span class="in">`plumbing`</span> and <span class="in">`total_pop`</span>.</span>
<span id="cb5-81"><a href="#cb5-81"></a></span>
<span id="cb5-82"><a href="#cb5-82"></a>I chose this dataset due to personal interest in water accessibility. I live in the California Central Valley which has struggled with water shortages and droughts for decades. I am interested in investigating and identifying demographic and economic factors that correlate with water insecurity and providing insight into the causes of water insecurity in my region and across the U.S.</span>
<span id="cb5-83"><a href="#cb5-83"></a></span>
<span id="cb5-84"><a href="#cb5-84"></a><span class="fu">## Questions</span></span>
<span id="cb5-85"><a href="#cb5-85"></a></span>
<span id="cb5-86"><a href="#cb5-86"></a>Two major questions I plan to investigate surround demographic factors and how the rate of water insecurity is changing over time.</span>
<span id="cb5-87"><a href="#cb5-87"></a></span>
<span id="cb5-88"><a href="#cb5-88"></a><span class="ss">- </span>What demographic and economic factors are correlated with higher and lower rates of water insecurity?</span>
<span id="cb5-89"><a href="#cb5-89"></a></span>
<span id="cb5-90"><a href="#cb5-90"></a><span class="ss">- </span>Which regions saw the biggest changes in water insecurity rates from 2022 to 2023? Did those regions improve or worsen? Does the presence of certain demographic, regional, or economic factors appear correlated to these changes in water insecurity rates?</span>
<span id="cb5-91"><a href="#cb5-91"></a></span>
<span id="cb5-92"><a href="#cb5-92"></a><span class="fu">## Analysis plan</span></span>
<span id="cb5-93"><a href="#cb5-93"></a></span>
<span id="cb5-94"><a href="#cb5-94"></a>For both of these questions, we will need to gather demographic data from the U.S. Census Bureau and will likely have to begin with answering question one to help inform our conclusions regarding question two. The following steps are proposed.</span>
<span id="cb5-95"><a href="#cb5-95"></a></span>
<span id="cb5-96"><a href="#cb5-96"></a><span class="fu">### Step 1: Identify and Download U.S. Census Bureau Data</span></span>
<span id="cb5-97"><a href="#cb5-97"></a></span>
<span id="cb5-98"><a href="#cb5-98"></a>The TidyTuesday dataset does not include any demographic information for U.S. counties aside from population. Because of this, we will have to use additional external data from the U.S. Census Bureau. We will gather demographic and income data from relevant counties, including the following parameters:</span>
<span id="cb5-99"><a href="#cb5-99"></a></span>
<span id="cb5-100"><a href="#cb5-100"></a>• Median Household Income</span>
<span id="cb5-101"><a href="#cb5-101"></a></span>
<span id="cb5-102"><a href="#cb5-102"></a>• % African American</span>
<span id="cb5-103"><a href="#cb5-103"></a></span>
<span id="cb5-104"><a href="#cb5-104"></a>• % Hispanic/Latino</span>
<span id="cb5-105"><a href="#cb5-105"></a></span>
<span id="cb5-106"><a href="#cb5-106"></a>• % White</span>
<span id="cb5-107"><a href="#cb5-107"></a></span>
<span id="cb5-108"><a href="#cb5-108"></a>• % Asian</span>
<span id="cb5-109"><a href="#cb5-109"></a></span>
<span id="cb5-110"><a href="#cb5-110"></a>•&nbsp;% Native</span>
<span id="cb5-111"><a href="#cb5-111"></a></span>
<span id="cb5-112"><a href="#cb5-112"></a><span class="fu">### Step 2: Complete Data Processing and Cleaning to Fully Integrate U.S. Census Bureau Data with TidyTuesday Dataset</span></span>
<span id="cb5-113"><a href="#cb5-113"></a></span>
<span id="cb5-114"><a href="#cb5-114"></a>Upon collecting all external data from the U.S. Census Bureau, we will complete data processing and cleaning to integrate all of the data into a single dataframe that we can use for analysis. This will include standardizing column names, removing extra data from counties not present in the TidyTuesday dataset, resolving issues with missing data, and any other data cleaning necessary to make the dataset easily usable for analysis.</span>
<span id="cb5-115"><a href="#cb5-115"></a></span>
<span id="cb5-116"><a href="#cb5-116"></a>All of the previously mentioned parameters will be added to the water insecurity datasets, and we will also manually create a region related parameter based on U.S. Census Bureau definitions.</span>
<span id="cb5-117"><a href="#cb5-117"></a></span>
<span id="cb5-118"><a href="#cb5-118"></a>• West: Washington, Oregon, California, Alaska, Hawaii, Montana, Idaho, Wyoming, Colorado, New Mexico, Arizona, Utah, Nevada</span>
<span id="cb5-119"><a href="#cb5-119"></a></span>
<span id="cb5-120"><a href="#cb5-120"></a>• South: Delaware, Maryland, District of Columbia, Virginia, West Virginia, North Carolina, South Carolina, Georgia, Florida, Kentucky, Tennessee, Mississippi, Alabama, Arkansas, Louisiana, Oklahoma, Texas</span>
<span id="cb5-121"><a href="#cb5-121"></a></span>
<span id="cb5-122"><a href="#cb5-122"></a>• Midwest: Ohio, Indiana, Illinois, Michigan, Wisconsin, Minnesota, Iowa, Missouri, North Dakota, South Dakota, Nebraska, Kansas</span>
<span id="cb5-123"><a href="#cb5-123"></a></span>
<span id="cb5-124"><a href="#cb5-124"></a>• Northeast: Maine, New Hampshire, Vermont, Massachusetts, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania</span>
<span id="cb5-125"><a href="#cb5-125"></a></span>
<span id="cb5-126"><a href="#cb5-126"></a><span class="fu">### Step 3: Addressing Question 1: Construct visualizations of Water Insecurity Rates against Demographic and Economic Parameters</span></span>
<span id="cb5-127"><a href="#cb5-127"></a></span>
<span id="cb5-128"><a href="#cb5-128"></a>Once data processing is completed and all new parameters are collected or created, we will create visualizations comparing our parameters to rates of water insecurity across all available counties. We will initially only work with the 2022 dataset.</span>
<span id="cb5-129"><a href="#cb5-129"></a></span>
<span id="cb5-130"><a href="#cb5-130"></a>The following visualization types are proposed:\</span>
<span id="cb5-131"><a href="#cb5-131"></a>\</span>
<span id="cb5-132"><a href="#cb5-132"></a>• Boxplots: Necessary to gather summarizing statistical information about all demographic groups and median income.</span>
<span id="cb5-133"><a href="#cb5-133"></a></span>
<span id="cb5-134"><a href="#cb5-134"></a>•&nbsp;Density Plots: Helpful at identifying clusters of data that the boxplots would fail to show.</span>
<span id="cb5-135"><a href="#cb5-135"></a></span>
<span id="cb5-136"><a href="#cb5-136"></a>• Linear Regression Plots: Tells us the specific strength of the relationship between water insecurity and demographics.</span>
<span id="cb5-137"><a href="#cb5-137"></a></span>
<span id="cb5-138"><a href="#cb5-138"></a><span class="fu">### Step 4: Addressing Question 2: Compare 2022 Data to 2023 Data Using the Same Methods to Determine Yearly Trends</span></span>
<span id="cb5-139"><a href="#cb5-139"></a></span>
<span id="cb5-140"><a href="#cb5-140"></a>After identifying any trends among the rate of water insecurity and our demographic and economic parameters, we can compare the year to year data to see if there are any changes from 2022 to 2023. We do have to be careful not to project too much based off this analysis since we're only looking at two years. However, we can use this data to identify any major changes that occur. Furthermore, we can use this opportunity to see if specific parameters are correlated with certain changes in water insecurity rates from 2022 and 2023.</span>
<span id="cb5-141"><a href="#cb5-141"></a></span>
<span id="cb5-142"><a href="#cb5-142"></a>We will examine which regions of the country saw the biggest shifts in rates of water insecurity. This will be done by using the three visualization methods mentioned previously to create 2022 and 2023 plots of counties in each region of the country and their rates of water insecurity. I will also create a new variable to calculate the change in the water insecurity rate from 2022 to 2023 to visualize that shift.</span>
<span id="cb5-143"><a href="#cb5-143"></a></span>
<span id="cb5-144"><a href="#cb5-144"></a>After this, we will also create side-by-side comparisons of the visualizations from Step 3 to see if any of our demographic or economic parameters are correlated with changes from 2022 to 2023.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>