{
  "hash": "e97a9c01d61aa0f04c04591750b21925",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Investigating Water Insecurity in the United States\"\nsubtitle: \"INFO 526 Final Project Proposal\"\nauthor:\n  - name: \"Jacob Caraccilo\"\n    affiliations:\n      - name: \"School of Information, University of Arizona\"\ndescription: \"Proposal for a data visualization project using the 2025 TidyTuesday Water Insecurity dataset to investigate patterns of water insecurity across U.S. counties.\"\nformat:\n  html:\n    code-tools: true\n    code-overflow: wrap\n    code-line-numbers: true\n    embed-resources: true\neditor: visual\ncode-annotations: hover\nexecute:\n  warning: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# provides glimpse at 2022 water insecurity data\nglimpse(water_insecurity_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 848\nColumns: 7\n$ geoid                    <chr> \"01069\", \"04001\", \"06037\", \"06097\", \"06001\", …\n$ name                     <chr> \"Houston County, Alabama\", \"Apache County, Ar…\n$ year                     <dbl> 2022, 2022, 2022, 2022, 2022, 2022, 2022, 202…\n$ geometry                 <chr> \"list(list(c(975267.980555021, 975512.9445474…\n$ total_pop                <dbl> 108079, 65432, 9721138, 482650, 1628997, 8978…\n$ plumbing                 <dbl> 93, 2440, 6195, 148, 808, 18, 128, 0, 123, 13…\n$ percent_lacking_plumbing <dbl> 0.08604817, 3.72906223, 0.06372711, 0.0306640…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# provides glimpse at 2023 water insecurity data\nglimpse(water_insecurity_2023)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 854\nColumns: 7\n$ geoid                    <chr> \"01003\", \"01069\", \"06037\", \"06087\", \"06097\", …\n$ name                     <chr> \"Baldwin County, Alabama\", \"Houston County, A…\n$ year                     <dbl> 2023, 2023, 2023, 2023, 2023, 2023, 2023, 202…\n$ geometry                 <chr> \"list(list(c(765297.99052762, 765703.76567671…\n$ total_pop                <dbl> 253507, 108462, 9663345, 261547, 481812, 1155…\n$ plumbing                 <dbl> 271, 30, 5248, 187, 308, 517, 4, 198, 1269, 8…\n$ percent_lacking_plumbing <dbl> 0.106900401, 0.027659457, 0.054308317, 0.0714…\n```\n\n\n:::\n:::\n\n\n## The TidyTuesday Water Insecurity Dataset\n\nThe 'Water Insecurity' Dataset was published on January 28th of 2025 for TidyTuesday and was curated by Niha Pereira. It explores household access to water across U.S. counties and allows us to investigate regional and population related patterns for water insecurity. Combined with demographic data, it can also provide insight into social and economic factors that may contribute to rates of water insecurity across the U.S.\n\nThe data includes two separate datasets for 2022 and 2023 each covering the extent of water insecurity (defined as a household lacking full plumbing infrastructure) in approximately 850 counties. This data is directly drawn from the U.S. Census Bureau and was developed through surveys of the public, meaning totals for those who are water insecure are estimates.\n\nThe 2022 data set includes 848 counties while the 2023 data set includes 854. They both contain 7 parameters:\n\n- `geoid`: A character variable of a unique county identifier code used by the U.S. Census Bureau.\n\n- `name`: A character variable of the name of the U.S. County.\n\n- `year`: A numerical variable of the year the data was collected (constant for each dataset).\n\n- `geometry`: A spatial geometry object that contains the geographic boundaries for each county in the dataset. Used to plot geographic maps of the U.S.\n\n- `total_pop`: A numerical variable representing the population of a given county.\n\n- `plumbing`: A numerical variable representing the estimated number of people in the county who are water insecure, defined as their household lacking full plumbing.\n\n- `percent_lacking_plumbing`: A numerical variable of the percent of people in a country who are water insecure, basically being a ratio of `plumbing` and `total_pop`.\n\nI chose this dataset due to personal interest in water accessibility. I live in the California Central Valley which has struggled with water shortages and droughts for decades. I am interested in investigating and identifying social, regional, and economic factors that correlate with water insecurity and providing insight into the causes of water insecurity in my region and across the U.S.\n\n## Questions\n\nTwo major questions I plan to investigate surround demographic factors and change to rates of water insecurity overtime.\n\n- What social, regional, and economic factors are correlated with higher and lower rates of water insecurity?\n\n- Which regions saw the biggest changes in water insecurity rates from 2022 to 2023? Did those regions improve or worsen? Does the presence of certain socioeconomic or regional factors appear relevant to improvements or worsening of water insecurity rates?\n\n## Analysis plan\n\nFor both of these questions, we will need to gather demographic data from the U.S. Census Bureau and will likely have to begin with answering question one to help inform our conclusions regarding question too. The following steps are proposed.\n\n### Step 1: Identify and Download U.S. Census Bureau Data\n\nThe TidyTuesday dataset does not include any demographic information for U.S. counties aside from population. Because of this, we will have to use additional external data from the U.S. Census Bureau. We will gather data regarding racial makeup and median income data for all U.S. counties included in our dataset.\n\n### Step 2: Complete Data Processing and Cleaning to Fully Integrate U.S. Census Bureau Data with TidyTuesday Dataset\n\nUpon collecting all external data from the U.S. Census Bureau, we will complete data processing and cleaning to integrate all of the data into a single dataframe that we can use for analysis. This will include standardizing column names, removing extra data from counties not present in the TidyTuesday dataset, resolving issues with missing data, and any other data cleaning necessary to make the dataset easily usable for analysis.\n\n### Step 3: Construct visualizations of Water Insecurity Rates against Demographic Information\n\nOnce data processing is completed, we can create visualizations to compare demographic information to rates of water insecurity across all available counties.\n\nDifference in parameterization of the racial and income data will be necessary. For racial makeup we will compare counties with 50% or greater of a specific group to water insecurity and examine difference among all racial groups. For median income, we will be more easily able to compare all counties at once, but may subdivide by specific income brackets to better analyze trends.\n\nThe following visualization types are proposed:\\\n\\\n• Boxplots: Necessary to gather summarizing statistical information about all racial groups and median income.\n\n• Density Plots: Helpful at identifying clusters of data that the boxplots would fail to show.\n\n• Linear Regression Plots: Tells us the specific strength of the relationship between water insecurity and demographics.\n\n### Step 4: Compare 2022 Data to 2023 Data Using the Same Methods to Determine Yearly Trends\n\nAfter identifying any interesting trends among water insecurity and demographics, we can compare the year to year data to see if there are any changes from 2022 to 2023. We do have to be careful not to project too much based off this analysis since we're only looking at two years. However, we can use this data to identify any major changes that occur. Furthermore, we can use this opportunity to see if specific demographics are related with certain changes in water insecurity from 2022 and 2023.\n\nCollectively, both these questions will tell us about which counties and which specific communities are struggling with water insecurity and how rates in water insecurity appear to be changing over time.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}